apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "seyoawe-app.fullname" . }}-cli-config
  labels:
    app.kubernetes.io/name: {{ include "seyoawe-app.name" . }}
    app.kubernetes.io/component: cli
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  ENGINE_URL: "http://{{ include "seyoawe-app.fullname" . }}-engine:{{ .Values.engine.service.port }}"
