apiVersion: v1
kind: Service
metadata:
  name: {{ include "seyoawe-app.fullname" . }}-engine
  labels:
    app.kubernetes.io/name: {{ include "seyoawe-app.name" . }}
    app.kubernetes.io/component: engine
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "seyoawe-app.name" . }}
    app.kubernetes.io/component: engine
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.engine.service.port }}
      targetPort: http
